import{i as S,S as w,a as f}from"./assets/vendor-527658dd.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const s={form:document.querySelector(".search-form"),formInput:document.querySelector(".form-input"),btn:document.querySelector(".search-button"),galleryList:document.querySelector(".gallery"),container:document.querySelector(".container"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".js-btn-load")};function p(){s.loader.classList.remove("hidden")}function g(){s.loader.classList.add("hidden")}const h="Sorry, there are no images matching your search query. Please try again!",M="We're sorry, but you've reached the end of search results.",P="Please enter correct information.";function d(t){S.error({message:t,position:"topRight"})}let u,y=new w(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function L(t){const o=t.hits.map(q).join("");u=t.totalHits,u>m&&s.btnLoadMore.classList.remove("hidden"),t.hits.length?s.galleryList.insertAdjacentHTML("beforeend",o):d(h),y.refresh()}function q(t){const{largeImageURL:o,webformatURL:i,tags:a,likes:e,views:r,comments:n,downloads:v}=t;return`<li class="gallery-item">
          <a href="${o}" class="gallery-link">
            <img
              src="${i}"
              class="gallery-image"
              alt="${a}"
            />
          </a>
          <div class="modal-text"> 
              <div class="modal-element"><p>Likes</p><span>${e}</span></div>
              <div class="modal-element"><p>Views</p><span>${r}</span></div>
              <div class="modal-element"><p>Comments</p><span>${n}</span></div>
              <div class="modal-element"><p>Downloads</p><span>${v}</span></div>
          </div>
        </li>`}const m=15;let l,c;async function $(t){if(t.preventDefault(),s.btnLoadMore.classList.add("hidden"),s.galleryList.innerHTML="",l=1,c=t.target.elements.input.value.trim(),c){try{p();const o=await b(c,l);L(o)}catch{d(h)}g(),s.form.reset()}else s.form.elements.input.value="",d(P)}async function b(t,o){const i="42271393-ceafa19bde7d0a63fb15d5d6f";f.defaults.baseURL="https://pixabay.com/api/";const a=`q=${t}&image_type=photo&orientation=horizontal&safesearch=true`,e=`?key=${i}&${a}`,r={params:{per_page:m,page:o}};return(await f.get(e,r)).data}async function E(){l+=1,p();const t=Math.ceil(u/m),o=await b(c,l);L(o),O(),g(),y.refresh(),l>=t&&(s.btnLoadMore.classList.add("hidden"),d(M))}function O(){const o=s.galleryList.firstElementChild.getBoundingClientRect().height*2;window.scrollBy({top:o,left:0,behavior:"smooth"})}s.form.addEventListener("submit",$);s.btnLoadMore.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
