import{i as v,S,a as f}from"./assets/vendor-527658dd.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const s={form:document.querySelector(".search-form"),formInput:document.querySelector(".form-input"),btn:document.querySelector(".search-button"),galleryList:document.querySelector(".gallery"),container:document.querySelector(".container"),loader:document.querySelector(".loader"),btnLoadMore:document.querySelector(".js-btn-load")};function w(){s.loader.classList.remove("hidden")}function p(){s.loader.classList.add("hidden")}const g="Sorry, there are no images matching your search query. Please try again!",M="We're sorry, but you've reached the end of search results.",P="Please enter correct information.";function c(t){v.error({message:t,position:"topRight"})}let u,h=new S(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(t){const o=t.hits.map(q).join("");u=t.totalHits,u>m&&s.btnLoadMore.classList.remove("hidden"),t.hits.length?s.galleryList.insertAdjacentHTML("beforeend",o):c(g),h.refresh()}function q(t){const{largeImageURL:o,webformatURL:a,tags:n,likes:e,views:r,comments:i,downloads:b}=t;return`<li class="gallery-item">
          <a href="${o}" class="gallery-link">
            <img
              src="${a}"
              class="gallery-image"
              alt="${n}"
            />
          </a>
          <div class="modal-text"> 
              <div class="modal-element"><p>Likes</p><span>${e}</span></div>
              <div class="modal-element"><p>Views</p><span>${r}</span></div>
              <div class="modal-element"><p>Comments</p><span>${i}</span></div>
              <div class="modal-element"><p>Downloads</p><span>${b}</span></div>
          </div>
        </li>`}const m=15;let d,l;async function $(t){if(t.preventDefault(),s.btnLoadMore.classList.add("hidden"),s.galleryList.innerHTML="",d=1,l=t.target.elements.input.value.trim(),l)try{const o=await L(l);return y(o)}catch{c(g)}finally{p(),s.form.reset()}else s.form.elements.input.value="",c(P)}async function L(t){w();const o="42271393-ceafa19bde7d0a63fb15d5d6f";f.defaults.baseURL="https://pixabay.com/api/";const a=`q=${t}&image_type=photo&orientation=horizontal&safesearch=true`,n=`?key=${o}&${a}`,e={params:{per_page:m,page:d}};return(await f.get(n,e)).data}async function E(){d+=1;const t=Math.ceil(u/m);if(d>=t)s.btnLoadMore.classList.add("hidden"),c(M);else{const o=await L(l),a=y(o);return O(),p(),h.refresh(),a}}function O(){const o=s.galleryList.firstElementChild.getBoundingClientRect().height*2;window.scrollBy({top:o,left:0,behavior:"smooth"})}s.form.addEventListener("submit",$);s.btnLoadMore.addEventListener("click",E);
//# sourceMappingURL=commonHelpers.js.map
